# Capítulo 1 — Python Essencial para Química Quântica

**Simulando Qubits com PySCF** · Cristiano Alves

Este *notebook* acompanha o Capítulo 1 do livro. Execute as células **na ordem**, de cima para baixo (`Shift+Enter`). Cada seção corresponde a uma seção do capítulo impresso.

> 💡 **Dica:** você pode rodar este *notebook* no **Google Colab** (sem instalar nada) ou localmente no **Jupyter** (via Anaconda).

## 1.2 Variáveis e tipos de dados

Uma **variável** é um nome que aponta para um valor guardado na memória. Criamos uma variável atribuindo um valor a um nome com o sinal de igual.

In [1]:
# Numero atomico e simbolo do hidrogenio
numero_atomico = 1
simbolo = "H"

# Energia do estado fundamental do atomo de H, em hartree
energia_fundamental = -0.5

# Numero de eletrons
n_eletrons = 1

print(simbolo, "tem", n_eletrons, "eletron e energia", energia_fundamental, "Ha")

H tem 1 eletron e energia -0.5 Ha


### Os tipos fundamentais

Quatro tipos básicos cobrem quase todas as nossas necessidades: inteiros (`int`), ponto flutuante (`float`), texto (`str`) e booleanos (`bool`). A função `type()` revela o tipo de qualquer valor.

In [2]:
carga = 0                 # int
distancia_HH = 0.74       # float, em angstrom
base = "sto-3g"           # str
convergiu = True          # bool

print(type(carga))        # <class 'int'>
print(type(distancia_HH)) # <class 'float'>
print(type(base))         # <class 'str'>
print(type(convergiu))    # <class 'bool'>

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


### Aritmética e a unidade atômica de energia

A química quântica trabalha em **unidades atômicas**: a unidade de energia é o *hartree* (Ha). Guarde a conversão **1 Ha ≈ 27,2114 eV**.

In [3]:
HARTREE_EM_EV = 27.2114        # constante de conversao

energia_H2_hartree = -1.11676  # energia da molecula H2 (Hartree-Fock/STO-3G)
energia_H2_eV = energia_H2_hartree * HARTREE_EM_EV

print("Energia da H2:", energia_H2_eV, "eV")

Energia da H2: -30.388603064 eV


> ⚠️ **Atenção:** a divisão `/` sempre produz um `float` em Python 3 (`4 / 2` → `2.0`). Para divisão inteira use `//`.

## 1.3 Estruturas de dados: listas, tuplas e dicionários

### Listas — coleções ordenadas e modificáveis

A **indexação começa em zero**; índices negativos contam a partir do fim.

In [4]:
# Energias dos orbitais moleculares (em hartree), do mais baixo ao mais alto
energias_orbitais = [-0.578, 0.670, 0.965, 1.410]

print("Numero de orbitais:", len(energias_orbitais))   # 4
print("Primeiro (indice 0):", energias_orbitais[0])    # -0.578
print("Ultimo (indice -1):", energias_orbitais[-1])    # 1.410

Numero de orbitais: 4
Primeiro (indice 0): -0.578
Ultimo (indice -1): 1.41


In [5]:
distancias = [0.70, 0.74, 0.80]   # distancias H-H em angstrom
distancias.append(0.90)           # adiciona ao final
distancias[0] = 0.72              # altera o primeiro elemento

print(distancias)                 # [0.72, 0.74, 0.8, 0.9]
print("Fatia [1:3]:", distancias[1:3])   # [0.74, 0.8]

[0.72, 0.74, 0.8, 0.9]
Fatia [1:3]: [0.74, 0.8]


### Tuplas — coleções imutáveis

Ideais para dados que formam uma unidade lógica, como as coordenadas $(x, y, z)$ de um átomo.

In [6]:
# Posicao de um atomo de hidrogenio (x, y, z) em angstrom
posicao_H = (0.0, 0.0, 0.371)

print("Coordenada z:", posicao_H[2])   # 0.371
# posicao_H[2] = 0.5   # ISTO GERARIA ERRO: tuplas sao imutaveis

Coordenada z: 0.371


### Dicionários — associam chaves a valores

A estrutura ideal para tabelas de propriedades. Silício (Si, Z=14) e fósforo (P, Z=15) são os protagonistas do nosso Projeto Âncora.

In [7]:
# Mapeia simbolo do elemento -> numero atomico
numeros_atomicos = {
    "H": 1, "C": 6, "N": 7, "O": 8, "Si": 14, "P": 15,
}

print("Numero atomico do fosforo:", numeros_atomicos["P"])   # 15
print("Elementos tabelados:", list(numeros_atomicos.keys()))

numeros_atomicos["Ga"] = 31        # adiciona nova entrada
print("Galio agora vale:", numeros_atomicos["Ga"])           # 31

Numero atomico do fosforo: 15
Elementos tabelados: ['H', 'C', 'N', 'O', 'Si', 'P']
Galio agora vale: 31


## 1.4 NumPy: o arsenal numérico

A mecânica quântica é, em essência, **álgebra linear**: estados são vetores, operadores são matrizes, energias são autovalores. O NumPy fornece o objeto `ndarray` e operações vetoriais rápidas. Por convenção, importamos com o apelido `np`.

In [8]:
import numpy as np

# Um vetor de energias orbitais
energias = np.array([-0.578, 0.670, 0.965, 1.410])

# Uma matriz 2x2 (por exemplo, um Hamiltoniano simples)
H = np.array([[0.0, -1.0],
              [-1.0, 0.0]])

print("Formato do vetor:", energias.shape)   # (4,)
print("Formato da matriz:", H.shape)         # (2, 2)

Formato do vetor: (4,)
Formato da matriz: (2, 2)


### Operações vetorizadas

Operações se aplicam a todos os elementos de uma vez, sem laços explícitos.

In [9]:
energias_hartree = np.array([-0.578, 0.670, 0.965, 1.410])

# Multiplica CADA elemento por 27.2114, de uma so vez
energias_eV = energias_hartree * 27.2114
print(energias_eV)

print("Energia minima:", energias_hartree.min())
print("Energia media:", energias_hartree.mean())
print("Soma das energias:", energias_hartree.sum())

[-15.7281892  18.231638   26.259001   38.368074 ]


Energia minima: -0.578
Energia media: 0.6167499999999999
Soma das energias: 2.4669999999999996


### Álgebra linear: o coração da mecânica quântica

Considere o Hamiltoniano de dois níveis
$$\hat{H} = \begin{pmatrix} 0 & -t \\ -t & 0 \end{pmatrix},$$
que descreve um elétron que pode ocupar dois sítios acoplados por uma amplitude de tunelamento $t$. Seus **autovalores** são as energias permitidas.

> ⚠️ Para matrizes simétricas/Hermitianas (todo Hamiltoniano físico), use `np.linalg.eigh`, não `eig`: é mais rápida e devolve autovalores reais ordenados.

In [10]:
t = 1.0
H = np.array([[0.0, -t],
              [-t,  0.0]])

# Para matrizes simetricas (Hermitianas), use eigh
autovalores, autovetores = np.linalg.eigh(H)

print("Energias (autovalores):", autovalores)   # [-1.  1.]
print("Estados (colunas):")
print(autovetores)

Energias (autovalores): [-1.  1.]
Estados (colunas):
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


## 1.5 Controle de fluxo: condicionais e laços

### Condicionais — `if` / `else`

> ⚠️ **Indentação é sintaxe.** Python usa o recuo (4 espaços) para delimitar blocos — não há chaves.

In [11]:
delta_energia = 3e-9   # variacao de energia no ultimo passo do SCF
limiar = 1e-8

if delta_energia < limiar:
    print("Convergiu! Podemos confiar no resultado.")
else:
    print("Ainda nao convergiu; aumente o numero de iteracoes.")

Convergiu! Podemos confiar no resultado.


### O laço `for`

A função `enumerate()` devolve o índice **e** o valor. As *f-strings* (`f"..."`) inserem variáveis no texto com formatação controlada.

In [12]:
energias_hartree = [-0.578, 0.670, 0.965, 1.410]

for i, e in enumerate(energias_hartree):
    e_eV = e * 27.2114
    print(f"Orbital {i}: {e:8.3f} Ha  =  {e_eV:8.2f} eV")

Orbital 0:   -0.578 Ha  =    -15.73 eV
Orbital 1:    0.670 Ha  =     18.23 eV
Orbital 2:    0.965 Ha  =     26.26 eV
Orbital 3:    1.410 Ha  =     38.37 eV


## 1.6 Funções e módulos

As **funções** encapsulam lógica sob um nome, permitindo reutilizá-la. Definimos com `def`; `return` entrega o resultado.

In [13]:
def hartree_para_eV(energia_hartree):
    """Converte uma energia de hartree para eletron-volt."""
    return energia_hartree * 27.2114

print(hartree_para_eV(-0.5))      # -13.6057
print(hartree_para_eV(-1.11676))  # -30.39...

-13.6057
-30.388603064


Funções podem ter argumentos com valores-padrão. Aqui reaproveitamos a diagonalização da seção anterior:

In [14]:
def energia_ligante(t=1.0):
    """Energia do estado ligante de um sistema de dois sitios,
    acoplados por uma amplitude de tunelamento t (em hartree)."""
    H = np.array([[0.0, -t],
                  [-t,  0.0]])
    autovalores = np.linalg.eigh(H)[0]
    return autovalores[0]   # o menor autovalor: estado fundamental

print(energia_ligante())      # -1.0  (usa t = 1.0, o padrao)
print(energia_ligante(0.5))   # -0.5

-1.0
-0.5


## 1.7 Ambientes de desenvolvimento

Você está usando um deles agora! Um *notebook* é um documento interativo de **células** de código e de texto (Markdown).

- **Jupyter Notebook** (local, via Anaconda): controle total, sem internet.
- **Google Colab** (nuvem, sem instalação): o caminho mais rápido para começar.

Atalhos: `Shift+Enter` executa e avança; `Ctrl+Enter` executa sem avançar. Comandos de sistema podem ser executados com `!` na frente, por exemplo `!pip install pyscf`.

## 1.8 Instalação do PySCF

O PySCF suporta plenamente **Linux** e **macOS**; no **Windows**, use **WSL** ou **Google Colab**.

Execute a célula abaixo para instalar o PySCF neste ambiente (só é preciso uma vez por sessão). No Colab, ela sempre funciona; localmente, ela já pode estar satisfeita.

In [15]:
# Descomente a linha abaixo se o PySCF ainda nao estiver instalado
# !pip install pyscf

## 1.9 Mãos à Obra: verificando a instalação

**Objetivo:** confirmar que Python, NumPy e PySCF estão prontos, imprimindo suas versões.

In [16]:
import numpy as np
import pyscf

print("NumPy versao:", np.__version__)
print("PySCF versao:", pyscf.__version__)
print("Ambiente pronto para a jornada!")

NumPy versao: 2.4.4
PySCF versao: 2.14.0
Ambiente pronto para a jornada!


Se você viu as três linhas acima sem mensagens de erro em vermelho, **parabéns**: seu laboratório computacional está montado.

> ⚠️ **Problemas comuns:** `ModuleNotFoundError: No module named 'pyscf'` → rode `!pip install pyscf`. No Colab, se a instalação não "pegar", reinicie pelo menu *Runtime → Restart runtime* e execute as células na ordem.

## 🔷 Projeto Âncora — Etapa 0: nasce o *notebook* mestre

O Projeto Âncora deste livro é a construção completa de um **qubit de spin em silício dopado com fósforo (Si:P)**. Cada capítulo acrescentará uma peça; a Etapa 0 é a fundação: um ambiente funcional.

A célula abaixo imprime, além das versões de NumPy e PySCF, também a versão do Python em execução.

In [17]:
import sys
import numpy as np
import pyscf

print("Python:", sys.version.split()[0])
print("NumPy :", np.__version__)
print("PySCF :", pyscf.__version__)
print()
print("Projeto Ancora Si:P - Etapa 0 concluida.")
print("Objetivo: construir, do zero, um qubit de spin em silicio:fosforo.")

Python: 3.11.7
NumPy : 2.4.4
PySCF : 2.14.0

Projeto Ancora Si:P - Etapa 0 concluida.
Objetivo: construir, do zero, um qubit de spin em silicio:fosforo.


**Ambiente escolhido:** _(anote aqui: Colab ou Jupyter, e por quê)_

No **Capítulo 2**, este mesmo *notebook* receberá seu primeiro cálculo de química quântica de verdade: a energia do átomo de silício.

## Exercícios

Resolva nas células abaixo. As soluções completas estão no repositório do livro.

**1.1 Conversões.** Crie uma variável com a energia −2,903 Ha (átomo de hélio). Converta-a para eV e imprima com uma *f-string*, 4 casas decimais.

**1.2 Dicionário de massas.** Monte um dicionário `{"H": 1.008, "Si": 28.09, "P": 30.97}`. Imprima a massa do fósforo e adicione o carbono (12,011).

**1.3 Varredura com `for`.** Crie uma lista de cinco distâncias de 0,70 a 0,90 Å (passo 0,05). Percorra-a e imprima cada distância convertida para bohr (÷ 0,529).

**1.4 Diagonalização.** Diagonalize $\hat H = \begin{pmatrix}\varepsilon & -t\\ -t & \varepsilon\end{pmatrix}$ com $\varepsilon = 0{,}2$, $t = 1{,}0$. Verifique que os autovalores valem $\varepsilon \pm t$.

**1.5 Função reutilizável.** Escreva `gap_HOMO_LUMO(energias, i_homo)` que devolva `energias[i_homo+1] - energias[i_homo]`. Teste com `[-0.578, 0.670, 0.965, 1.410]` e HOMO no índice 0.

**1.6 Projeto Âncora.** Acrescente uma célula que também imprima a versão do Python (`import sys; print(sys.version)`).

In [18]:
# 1.1 Conversoes

In [19]:
# 1.2 Dicionario de massas

In [20]:
# 1.3 Varredura com for

In [21]:
# 1.4 Diagonalizacao

In [22]:
# 1.5 Funcao reutilizavel